import {
  Anchor,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  AlertTriangle,
  Award,
  Barcode,
  BadgeCheck,
  BarChart3,
  Bell,
  BellPlus,
  Bot,
  Building2,
  Calculator,
  Calendar,
  CheckCircle2,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Download,
  Edit3,
  ExternalLink,
  Factory,
  FileSignature,
  FileText,
  FileUp,
  FolderArchive,
  FolderCheck,
  Gavel,
  Globe,
  Handshake,
  HelpCircle,
  History,
  IdCard,
  Image,
  ImagePlus,
  Info,
  Languages,
  LayoutDashboard,
  Leaf,
  Lightbulb,
  ListFilter,
  Lock,
  MailWarning,
  MapPin,
  Menu,
  MessageCircle,
  MessagesSquare,
  NotebookPen,
  Package,
  Paperclip,
  PanelLeftClose,
  Pen,
  PenTool,
  Pencil,
  Radar,
  Receipt,
  RefreshCw,
  RotateCcw,
  Save,
  ScrollText,
  SearchX,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBasket,
  Ship,
  SlidersHorizontal,
  Sparkles,
  Tag,
  Trash2,
  TrendingUp,
  Trophy,
  Truck,
  Type,
  UserSearch,
  Wallet,
  Wrench,
  X,
  type LucideIcon,
} from "lucide-react"

export const iconMap: Record<string, LucideIcon> = {
  anchor: Anchor,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_drop_down: ChevronDown,
  attach_file: Paperclip,
  auto_awesome: Sparkles,
  add_alert: BellPlus,
  add_photo_alternate: ImagePlus,
  analytics: BarChart3,
  badge: IdCard,
  bar_chart: BarChart3,
  barcode: Barcode,
  calculate: Calculator,
  calendar_today: Calendar,
  category: Tag,
  chat_bubble: MessageCircle,
  check: Check,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  dashboard: LayoutDashboard,
  delete: Trash2,
  description: FileText,
  directions_boat: Ship,
  domain: Building2,
  download: Download,
  draw: PenTool,
  eco: Leaf,
  edit: Pencil,
  edit_document: Edit3,
  edit_note: NotebookPen,
  equalizer: SlidersHorizontal,
  expand_more: ChevronDown,
  fact_check: ShieldCheck,
  factory: Factory,
  filter_list: ListFilter,
  folder_managed: FolderCheck,
  folder_zip: FolderArchive,
  forum: MessagesSquare,
  gavel: Gavel,
  gesture: Pen,
  handshake: Handshake,
  help: HelpCircle,
  history: History,
  image: Image,
  info: Info,
  inventory_2: Package,
  language: Globe,
  lightbulb: Lightbulb,
  local_shipping: Truck,
  location_on: MapPin,
  lock: Lock,
  mail_lock: MailWarning,
  menu: Menu,
  menu_open: PanelLeftClose,
  military_tech: Award,
  notifications: Bell,
  open_in_new: ExternalLink,
  payments: Wallet,
  person_search: UserSearch,
  picture_as_pdf: FileText,
  policy: ScrollText,
  public: Globe,
  radar: Radar,
  receipt_long: Receipt,
  refresh: RotateCcw,
  request_quote: FileSignature,
  restart_alt: RotateCcw,
  save: Save,
  schedule: Clock,
  search_off: SearchX,
  security: Shield,
  send: Send,
  send_and_archive: Send,
  settings: Settings,
  shield_lock: ShieldCheck,
  shopping_basket: ShoppingBasket,
  smart_toy: Bot,
  sort: ArrowUpDown,
  sync: RefreshCw,
  text_fields: Type,
  translate: Languages,
  troubleshoot: Wrench,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  upload_file: FileUp,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  warning: AlertTriangle,
  workspace_premium: Trophy,
}

export function getIcon(name: string | undefined | null): LucideIcon {
  if (!name) return HelpCircle
  return iconMap[name] ?? HelpCircle
}
